name: Ply CT
description: Ply autotest execution and status badge
branding:
  icon: play
  color: blue
inputs:
  plyees:
    description: Glob pattern(s) for requests/flows/cases (otherwise all ply tests)
    required: false
  cwd:
    description: Working directory for ply execution
    required: false
    default: '.'
  ply-path:
    description: 'Path to ply package (eg: node_modules/ply-ct/dist)'
    required: false
    default: node_modules/ply-ct/dist
  result-file:
    description: Result file in case Ply tests were already run in a previous workflow/job
    required: false
  badge-branch:
    description: 'Branch to contain status badge (eg: "badge"). Needed to display Ply badge for private repositories.'
    required: false
  badge-path:
    description: Save badge to this file path (relative to repo root). Only used with badge-branch.
    required: false
    default: ply-badge.svg
  github-token:
    description: GitHub token for pushing badge updates. Required if badge-branch input is specified.
    required: false
outputs:
  ply-result:
    description: Ply test result summary
runs:
  using: node12
  main: './dist/index.js'

