name: 'ply'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 'true'
    steps:
    - uses: actions/checkout@v2
    - uses: ./
