name: 'ply'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  ply:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 'true'
      PLY_VALUES: ${{ secrets.PLY_VALUES }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - uses: ./
